### PR TITLE
Links: Failing test for empty belongs_to

### PR DESCRIPTION
**Pull request by ziggurat**

### CODE REVIEW

**Comment by richmolj** [comment]
Looks great, thanks! Minor, but could you make this `.update_attributes` instead of `.create`? https://github.com/graphiti-api/graphiti/blob/acb06fda1aa34a96d2ca86b0a141fd2d45444da4/spec/serialization_spec.rb#L1224

The reasoning is this way we're only updating the bit of information relevant to the test, instead of redefining the whole object and possibly getting an unexpected side effect

**Comment by ziggurat** [comment]
Yes! My bad! Will change it as soon as I can.

**Comment by ziggurat** [comment]
Changed!

**Comment by richmolj** [comment]
Fixed in master!

**Pull request closed without merging**
