### PR TITLE
Allow attribute guard to receive name

### PR DESCRIPTION
**Pull request by seocahill**
We have a use case whereby our authorization is quite granular, i.e. we tailor payloads based on a user/role per request.

This PR would allow attribute guard methods to optionally receive the name of the current attribute in addition to the current object.

```ruby
attribute :foo, :string, readable: :bar?

def bar?(object, attribute)
   # Check if current user has a permission allowing them to read foo attribute
   authorize_attribute(context.current_user, attribute) #=> false
end
```

I realize not many applications will require this level of granularity but it seems like a relatively minor change in the scheme of things so I thought I'd ask anyway.

### CODE REVIEW

**Comment by Zooip** [comment]
I would definitely use this. When using ActiveModel::Serializer,  I delegate read authorizations to a `can_read_attribute?(attribute_name)` on my associated PunditPolicy. I was wondering how I could do that on Graphiti ...

**Comment by richmolj** [comment]
@seocahill don't we need to address https://github.com/graphiti-api/graphiti/pull/240 before this?

**Comment by seocahill** [comment]
@richmolj #240 is unrelated AFAIK. 

Do we think this is a good idea, should I add documentation?

**Comment by richmolj** [comment]
Sorry for the delay @seocahill this is 💯

**Comment by richmolj** [comment]
Released in `1.2.29`

**Pull request merged**
