### PR TITLE
Remove the upper bound of the ruby version

### PR DESCRIPTION
**Pull request by calebuharrison**
Also fixes specs that are currently failing.

### CODE REVIEW

**Comment by richmolj** [comment]
Hm, I think we need to add 3.x [here](https://github.com/graphiti-api/graphiti/blob/master/.travis.yml#L3-L6) for this, though I'm not sure why CI has stopped running on this PR

**Comment by calebuharrison** [comment]
> Hm, I think we need to add 3.x [here](https://github.com/graphiti-api/graphiti/blob/master/.travis.yml#L3-L6) for this, though I'm not sure why CI has stopped running on this PR

Added!

**Comment by richmolj** [comment]
@wadetandy do you happen to know what happened to CI running on PRs?

**Comment by smai-f** [comment]
Hey @richmolj , I believe CI stopped running because an admin has to switch the project to travis-ci.com instead of travis-ci.org (you can see in the header [here](https://travis-ci.org/github/graphiti-api/graphiti))

https://docs.travis-ci.com/user/migrate/open-source-repository-migration/

**Comment by richmolj** [comment]
@smai-f thanks so much - forgive me I'm short on time, where do I make the change?

**Comment by smai-f** [comment]
@richmolj AFAIK log in here and you should see a button to migrate this project to travis-ci.com, should be fast: https://travis-ci.org/account/repositories  - if that doesn't work then I think you'd have to follow [these instructions](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#migrating-a-repository).

The only reference to travis-ci.org in the graphiti repo that would need to be updated after is [line 1 of the README](https://github.com/graphiti-api/graphiti/blob/master/README.md?plain=1#L1).

Last, if you use the Travis CLI or Travis CI API locally you'd need to make [these changes](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#do-i-need-to-make-any-other-changes). It does not appear these are used within graphiti.

**Comment by richmolj** [comment]
Unfortunately there is no button (there is a message) and the instructions point to https://www.travis-ci.com/account/migrate which is a 404 😬

**Comment by smai-f** [comment]
@richmolj Haha, classic. I suspect this might be the ticket then, starting from travis-ci.com instead of travis-ci.org - https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#migrating-a-repository

**Comment by richmolj** [comment]
Screen Shot 2021-12-21 at 12 01 58 PM

ugh...

**Comment by richmolj** [comment]
Actually just bad UI bug. I have now successfully clicked migrate. Let me try close and reopen

**Comment by richmolj** [comment]
Not sure why it's not running...sorry im just trying things as I run xmas errands, @wadetandy do you know how to make it work?

**Comment by richmolj** [comment]
Aha there we go...

**Comment by wagenet** [comment]
I tried to get this working but it's been a challenge.

**Comment by richmolj** [comment]
Ugh thanks for the effort @wagenet, any suggestions on how we should proceed?

**Comment by wagenet** [comment]
@richmolj I’m splitting up some of the upgrades.

**Comment by wagenet** [comment]
This is good to go except for the fact that Travis doesn't support Ruby 3.1 still...

**Comment by wagenet** [comment]
Resolved in #406. Thanks!

**Pull request closed without merging**
