### PR TITLE
Treat empty strings for expected integers as nil

### PR DESCRIPTION
**Pull request by elDub**
Allow nullification of integer attributes when empty string is passed.

### CODE REVIEW

**Comment by richmolj** [comment]
This looks great @elDub, thanks ❤️ ! I think the only thing this needs is to cover the other types as well?

**Comment by elDub** [comment]
I added similar code to other numerics and added/updated tests.

**Comment by richmolj** [comment]
I think the biggest consideration is performance because we'd be calling `#blank?` a bunch more times and most people aren't using [fast_blank?](https://github.com/SamSaffron/fast_blank).

Another scenario: it makes sense that *filtering* wants this behavior, but I could see serializing `null` instead of `""` to be a surprising result.

@wadetandy thoughts?

**Comment by wadetandy** [comment]
Is the `blank?` check actually the right one?:

```ruby
"".blank? # => true
"".empty? # => true
"    ".blank? # => true
"    ".empty? # => false
```

Not only is the `empty?` check _much_ faster, but it's more correct for the intended use-case.

**Comment by wadetandy** [comment]
Stepping back from a second from the specific implementation details, I'd like to ask a bit about this from an API usability perspective.  Curious as to what pain you find with the current way of passing either `null` or omitting a key entirely to null a particular number field?  Is it providing some unexpected behavior?  I see this path also potentially providing unexpected behavior so want to understand the problem a bit better.

**Comment by elDub** [comment]
Then is this a problem with Spraypaint? When I clear out a numeric value in the client using Spraypaint, it passes an empty string which is failing in Graphiti when the attribute is defined as `:integer`.

**Comment by wadetandy** [comment]
When you say "clearing out", how do you mean? Are you binding the field directly to a text input, or are you setting it to `null` directly in javascript?  The latter case behaves as expected in the test suite, but the former may need an enhancement.

**Comment by elDub** [comment]
I am binding the field to a text input in VueJS.

**Comment by elDub** [comment]
So your change will make it send this?
```attributes: {numberfield: null}```

Instead of this?
```attributes: {numberfield: ""}```

Does Spraypaint have a way to define what type an attribute is, or will this change apply to _all types_, meaning if someone clears out a regular string value in the UI that it too will receive `null`?

**Comment by wadetandy** [comment]
Per [this PR](https://github.com/graphiti-api/spraypaint.js/pull/12), we will actually listen when you specify the type of the attribute:

```javascript
class Person extends ApplicationRecord {
  @Attr firstName
  @Attr({ type: Number }) age
}
```

If a field of type `Number` is an empty string, it will send `null` to the server on persist.

Note that this does not handle the filtering use-case.  `Person.where({ 'age': null })` will currently drop the filter altogether.

**Comment by elDub** [comment]
Cool. I was not aware of the `type:` option for an attribute. Should this also be available for date objects?

**Comment by wadetandy** [comment]
@elDub I think in the medium term, yes, but those are a bit more of an issue since there's both serialization and deserialization casting to handle (the wire sees them as just strings).  I'd rather not tackle that the way this part of the codebase currently works, and I've got a general (de)serialization cleanup/rework I'm planning to handle in the near future.

**Comment by wadetandy** [comment]
@elDub Just pushed [spraypaint 0.5.0](https://github.com/graphiti-api/spraypaint.js/releases/tag/v0.5.0), which has the fix for this issue.  If this fixes your issue then I think we can close this PR.  You may still need to manually null out your empty string dates for the time being though.

**Comment by wadetandy** [comment]
Closing, as we've added a fix to spraypaint for this behavior.

**Pull request closed without merging**
