### PR TITLE
Handle invalid item_counts for #last_page method

### PR DESCRIPTION
**Pull request by sideshowbandana**
- Ensure that #item_count always returns an integer.
- Add specs for page_size and item_count being set to 0
- Add spec for item_count when resource.stat returns nil

FIXES: https://github.com/graphiti-api/graphiti/issues/82

### CODE REVIEW

**Comment by sideshowbandana** [comment]
@richmolj I took a stab at addressing #82. It's a bit odd to me how it occurred though...

https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/delegates/pagination.rb#L49-L58 should prevent `@item_count` from ever being nil unless for some reason `nil.kind_of?(Numeric)` is returning true?

I've also removed the spec_helper changes. Those weren't supposed to be submitted as part of the PR. However, I am curious what pattern you would like me to follow for shared_contexts. Currently I'm using a require_relative https://github.com/graphiti-api/graphiti/blob/master/spec/delegates/pagination_spec.rb#L2. It looks like the other shared_contexts are brought in via `graphiti_spec_helpers` Should I make a PR that moves that code ? What's the process for making multiple dependent changes?

**Comment by richmolj** [comment]
> should prevent @item_count from ever being nil 

I believe this is because `@item_count` instance variable is the correct value, but `item_count` is not. The method isn't returning `@item_count`, it's returning the result of the `unless` block. We should probably try to remove some of the spec stubbing to expose this issue.

For shared context, does `spec/support/pagination_link_helper.rb` work?

**Comment by sideshowbandana** [comment]
> it's returning the result of the `unless` block.

Ah. That's it. I thought I had a return statement at the end.  >_<

Updated the patch and renamed the spec helper

**Review by richmolj — APPROVED** [review]
Thanks for addressing this!

**Pull request merged**
