### PR TITLE
Fix Issue #124

### PR DESCRIPTION
**Pull request by mihaimuntenas**
Base#deserialized_params to always return a Deserializer object

### CODE REVIEW

**Comment by wadetandy** [comment]
@mihaimuntenas This looks like a good fix for the issue.  Would you mind adding a spec (probably makes sense in the `spec/integration/rails` section) which validates the fix? I'm doing some refactoring in this area soon for a separate feature and I don't want to accidentally rebreak this when I do.

**Comment by mihaimuntenas** [comment]
@wadetandy Will check how I can hook into the existent one, from:
https://github.com/graphiti-api/graphiti/blob/master/spec/integration/rails/persistence_spec.rb#L140

Really strange that this one actually did not fail in the first place.

**Comment by mihaimuntenas** [comment]
@wadetandy the issue was caused by the following line of code:
https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/railtie.rb#L77

Any suggestion where I can place a spec for this ?
Will also search on my own, but any suggestion would be appreciated.

**Comment by mihaimuntenas** [comment]
@wadetandy I suppose this is the cause that the actual spec did not catch this:

https://github.com/graphiti-api/graphiti/blob/master/spec/support/rails/employee_controller.rb#L38

this line should read ` render jsonapi_errors: employee` to actually trigger the rendering block setup by the railtie.

Would it be ok to just update this line ?

**Comment by mihaimuntenas** [comment]
PS: same applies generally for tendering the errors in this mock controller (for update and create).

**Comment by mihaimuntenas** [comment]
@wadetandy Updated the specs for persistence in specs/rails/integration. Switched all error rendering to use the `render jsonapi_errors: employee`, relying on graphiti_errors implementation.
Can confirm, that without the fix, the #destroy fails with the issue, as expected.

**Review by richmolj — COMMENTED** [review]
This looks good to me, great work @mihaimuntenas! 👏 

@wadetandy all good for you?

**Comment by wadetandy** [comment]
Looks great!

**Comment by richmolj** [comment]
Released in `1.0.2`

**Pull request merged**
