### PR TITLE
Properly excape prefix and suffix queries

### PR DESCRIPTION
**Pull request by wadetandy**
In #196 I added sanitization for `match` filters but I negelected
to handle `prefix` and `suffix` filters, which share similar logic.
This handles all three.  Additionally, issue #207 indicates an issue
with the `sanitize_sql_like` method not always being available on the
scope object. Wasn't able to reproduce myself, but this switches to
avoid using the method from scope directly and instead creates a utility
class which is extended with the appropriate sanitization methods.

### CODE REVIEW

**Comment by jackcasey** [comment]
Thanks!

I had a quick try of this fix and unfortunately it still doesn't work (in rails 5.1.7 at least) because even via the concern being mixed in that method is private:

```
NoMethodError (private method `sanitize_sql_like' called for Graphiti::Adapters::ActiveRecord::Sanitizer:Class):

/Users/jack/dev/graphiti/lib/graphiti/adapters/active_record.rb:316:in `block in sanitized_like_for'
/Users/jack/dev/graphiti/lib/graphiti/adapters/active_record.rb:314:in `map'
/Users/jack/dev/graphiti/lib/graphiti/adapters/active_record.rb:314:in `sanitized_like_for'
/Users/jack/dev/graphiti/lib/graphiti/adapters/active_record.rb:65:in `filter_string_match'
```

I will help with the fix seeing as you can't repro but I need to head off for today. 👋

**Comment by wadetandy** [comment]
@jackcasey Try now.  Turns out I thought our appraisal suite was testing all of rails 5.0, 5.1, and 5.2 but was only testing against 5.2.  Added appraisals for older rails versions and revealed the problem, which i fixed

**Comment by jackcasey** [comment]
@wadetandy Works great thanks!

**Comment by jackcasey** [comment]
Can probably be closed now btw, as #219 is merged.

**Pull request closed without merging**
