### PR TITLE
Fix Issue #62

### PR DESCRIPTION
**Pull request by mihaimuntenas**
Resolve polymorphic child resource before typecasting attributes.

### CODE REVIEW

**Comment by richmolj** [comment]
Looks great, thanks for this PR ❤️ Do you think you could add a test?

**Comment by richmolj** [comment]
I'm actually trying to leave the Util classes more or less private, and instead test the real-world functionality. I think we could do this in [polymorphic_resource_spec.rb](https://github.com/graphiti-api/graphiti/blob/master/spec/polymorphic_resource_spec.rb) or [polymorphism_spec.rb](https://github.com/graphiti-api/graphiti/blob/master/spec/polymorphism_spec.rb), what do you think?

**Comment by mihaimuntenas** [comment]
Well, my issue showed up only when the Persistence instance was created, before it was run, from within the Resource ... 
I also checked a bit the Resource.build, to build a derived resource through the base one, but the resulting Proxy, had the Resource of the base type, not of the derived type (which is somehow in line with ActiveRecord). In the end, the not-persisted object of the base resource can be transformed to a different derived one (eg: initialize a CreditCard with Visa attributes, you should still be able to change it to a MasterCard - the actual "locking" of the type should be done upon persistence).
Given this, that the actual polymorphic class is determined within the Persistence and not upon building the Resource, made me implement the spec on Persistence, rather than Resource.

**Comment by mihaimuntenas** [comment]
I also added some specs for the public API.
Though, even if the Persistance class should be private API, I would still keep the specs for that - as the actual determination is done there and the issue (sequence of operations) was within the initializer of the Persistence class.

**Comment by richmolj** [comment]
Works for me, thanks a bunch! ❤️

**Pull request merged**
