### PR TITLE
Fixes version check for ActiveRecord adapter introduced in #478

### PR DESCRIPTION
**Pull request by mihaimuntenas**
Fixes version check for ActiveRecord version, introduced in #478, that's causing an ArgumentError, as the target version for the comparison is expected to be a String not a Number.

@jkeen

### CODE REVIEW

**Comment by mihaimuntenas** [comment]
@jkeen I have no idea how this passed the tests ... 
I see this issue on Ruby 3.2.1 with Rails 7.2.1 in my projects.

**Comment by mihaimuntenas** [comment]
@richmolj @wadetandy @jkeen any maintainers who can review, merge, and release a new version? please ...

**Comment by jkeen** [comment]
@mihaimuntenas Missed the notification on this, sorry for delay! 

Also have no idea how that passed tests, but thanks for catching it and supplying a fix.

**Comment by mihaimuntenas** [comment]
@jkeen thanks a lot! If you can also do a . release would be great. 
The bot failed to do it automatically, seems there's a spec failing for ruby 3.1 & rails 7 - but looks unrelated.

**Comment by jkeen** [comment]
Ack, yeah that's an intermittent error, just reran that test—releasing now.

**Pull request merged**
